#!/usr/bin/env sh

CONFIG=~/.docker/config.json

[ -e "${CONFIG}" ] && cat "${CONFIG}"

mkdir -p "$(dirname "${CONFIG}")" && echo '{"experimental":"enabled"}' > "${CONFIG}"

[ -e "${CONFIG}" ] && cat "${CONFIG}"

uname -a

wget -q https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O buildx
chmod +x buildx

./buildx inspect --bootstrap

exit 1

docker build \
    --label org.label-schema.build-date=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --label org.label-schema.vcs-ref=`git rev-parse --short HEAD` \
    --label org.label-schema.vcs-url="https://github.com/Gerrit-K/ytt-docker" \
    --label org.label-schema.version="${SOURCE_BRANCH}" \
    --label org.label-schema.schema-version="1.0" \
    --build-arg YTT_VERSION="${SOURCE_BRANCH}" \
    -f "${DOCKERFILE_PATH}" \
    -t "${IMAGE_NAME}" \
    .
